Namespace CardonerSistemas

    Module ConstantsKeys
        Friend Const BACKSPACE As String = "{BACKSPACE}"
        Friend Const BREAK As String = "{BREAK}"
        Friend Const CAPSLOCK As String = "{CAPSLOCK}"
        Friend Const DELETE As String = "{DELETE}"
        Friend Const DOWN As String = "{DOWN}"
        Friend Const ENDKEY As String = "{END}"
        Friend Const ENTER As String = "{ENTER}"
        Friend Const ESC As String = "{ESC}"
        Friend Const HELP As String = "{HELP}"
        Friend Const HOME As String = "{HOME}"
        Friend Const INSERT As String = "{INSERT}"
        Friend Const LEFT As String = "{LEFT}"
        Friend Const NUMLOCK As String = "{NUMLOCK}"
        Friend Const PGDN As String = "{PGDN}"
        Friend Const PGUP As String = "{PGUP}"
        Friend Const PRTSC As String = "{PRTSC}"
        Friend Const RIGHT As String = "{RIGHT}"
        Friend Const SCROLLLOCK As String = "{SCROLLLOCK}"
        Friend Const TAB As String = "{TAB}"
        Friend Const UP As String = "{UP}"
        Friend Const F1 As String = "{F1}"
        Friend Const F2 As String = "{F2}"
        Friend Const F3 As String = "{F3}"
        Friend Const F4 As String = "{F4}"
        Friend Const F5 As String = "{F5}"
        Friend Const F6 As String = "{F6}"
        Friend Const F7 As String = "{F7}"
        Friend Const F8 As String = "{F8}"
        Friend Const F9 As String = "{F9}"
        Friend Const F10 As String = "{F10}"
        Friend Const F11 As String = "{F11}"
        Friend Const F12 As String = "{F12}"
        Friend Const F13 As String = "{F13}"
        Friend Const F14 As String = "{F14}"
        Friend Const F15 As String = "{F15}"
        Friend Const F16 As String = "{F16}"
        Friend Const ADD As String = "{ADD}"
        Friend Const SUBTRACT As String = "{SUBTRACT}"
        Friend Const MULTIPLY As String = "{MULTIPLY}"
        Friend Const DIVIDE As String = "{DIVIDE}"

        Friend Const SHIFT As String = "+"
        Friend Const CONTROL As String = "^"
        Friend Const ALT As String = "%"

        Friend Const UserDefinedCLEAR As String = "{CLEAR}"
        Friend Const UserDefinedSPACE As String = "{SPACE}"

    End Module

End Namespace